### ISSUE TITLE
NHSbuntu 'Developer Edition'

### ISSUE THREAD

**Issue by pacharanero** [NHSbuntu/nhsbuntu-default-settings#12]
Having seen how many people at NHS Digital are using Ubuntu in VMs, I think there might be a reasonable take-up of a pre-configured NHSbuntu with a few additions to make it more useful out of the box. Alternatively these could be handled as part of a metapackage

## preinstalled
* Git from the git-core PPA (much more up to date than the Git in Ubuntu repos)
* Virtualbox
* Vagrant
* Docker
* possibly some of the more frequently used IDEs
* virtualenvwrapper and some virtualenvs
* nvm, node, npm etc
* smart card drivers & NHSbuntu identity agent

## preconfigured
* default user is added to `vboxuser` and `docker` groups

**Comment by robdyke** [comment]
Closing. Migrate to NHoS.
