### ISSUE TITLE
Ability to run Java based applications

### ISSUE THREAD

**Issue by PaoloVecchi** [NHSbuntu/nhsbuntu-default-settings#13]
NPAPI has been finally removed from Firefox and Chrome/Chromium but some unfortunate users still need to run Java based legacy applications through a web browser until suppliers are changed or decide to join us in the XXI century.
Today I tested Pale Moon (palemoon.org), a Mozilla based browser which kept NPAPI support, together with IcedTea, a JRE available from the standard Ubuntu repositories, and a legacy application that uses Java worked perfectly on Ubuntu 16.04/16.10.

Could Pale Moon and IcedTea be added to NHSbuntu to provide support foo legacy applications while users find more modern suppliers?

**Comment by robdyke** [comment]
Closing. Migrated to NHoS.
